
import React from 'react';

const Privacy: React.FC = () => {
  return (
    <div className="container mx-auto px-4 py-20 max-w-4xl">
      <h1 className="text-3xl font-bold mb-8 text-slate-900">Privacy Policy</h1>
      <div className="prose prose-slate max-w-none text-slate-600">
        <p className="mb-4">Last Updated: October 2023</p>
        <h2 className="text-xl font-bold mt-8 mb-4">1. Information We Collect</h2>
        <p>We do not collect personal identifying information unless you voluntarily provide it through our contact form. We do use industry-standard cookies to analyze traffic and provide personalized advertisements.</p>
        
        <h2 className="text-xl font-bold mt-8 mb-4">2. AI Generated Content</h2>
        <p>The names and content generated by our tool are produced by Google's Gemini AI. We do not store the specific keywords you enter on our servers for long-term use; they are processed temporarily to provide the requested results.</p>

        <h2 className="text-xl font-bold mt-8 mb-4">3. Advertising</h2>
        <p>We use Google AdSense and other third-party vendors to serve ads. These vendors may use cookies to serve ads based on your previous visits to this or other websites.</p>

        <h2 className="text-xl font-bold mt-8 mb-4">4. Your Rights</h2>
        <p>You have the right to request access to any personal data we may hold, though as a utility tool, we hold very little personal data by default.</p>
      </div>
    </div>
  );
};

export default Privacy;
